erDiagram
    USER ||--|| USER-NAME : has
    USER ||--|| EMAIL : has

    USER ||--0| PROJECT : responsible-for
    USER ||--0| MODEL : responsible-for


    MODEL ||--|| NAME : has
    MODEL ||--|| CHECKPOINT : has


    PROJECT ||--|| START-DATE : has
    PROJECT ||--|| STOP-DATE : has
    PROJECT ||--|| DESCRIPTION : has
    PROJECT ||--|| DESCRIPTION : has

    PROJECT ||--|{ INTEREST : contains
    PROJECT ||--|{ DATASET : contains
    PROJECT ||--|{ MODEL : uses


    INTEREST ||--|| NAME : has


    DATASET ||--|| NAME : has
    DATASET ||--|| FILE-TYPE : has
    DATASET ||--|| FILE-LOCATION : has
    DATASET ||--|| RESOLUTION-X : has
    DATASET ||--|| RESOLUTION-Y : has
    DATASET ||--|| RESOLUTION-Z : has
    DATASET ||--|| MODALITY : has

    DATASET ||--0{ ANNOTATION : contains
    DATASET ||--0{ SEGMENTATION : contains


    ANNOTATION ||--|| FILE-TYPE : has
    ANNOTATION ||--|| FILE-LOCATION : has
    ANNOTATION ||--|| NAME : has

    ANNOTATION ||--|| USER : annotated-by
    ANNOTATION ||--0| SEGMENTATION : from-segmentation


    SEGMENTATION ||--|| FILE-TYPE : has
    SEGMENTATION ||--|| FILE-LOCATION : has
    SEGMENTATION ||--|| NAME : has

    SEGMENTATION ||--|| MODEL : from-model
