flowchart LR
    subgraph disk[Disk storage]
    ann[(annotations)]
    raw[(raw EM data)]
    segs[(segmentations)]
    models[(AI models)]
    end

    subgraph backend
    b1[backend]
    queue[queue]
    b1<-->|Use/Edit data| disk
    b1<-->|Create/Poll tasks|queue
    end

    subgraph workers
    gpu_worker[GPU Worker]
    queue<-->|Retrain/Segment| gpu_worker
    gpu_worker<-->|Use/Create data| disk
    convert_worker[Conversion Worker]
    queue<-->|Convert datasets| convert_worker
    convert_worker<-->|Use/Create dataset| raw
    end

    subgraph frontend
    UI
    UI-->|Commands/Edits|b1
    b1-->|Visualizations|UI
    subgraph uis[UI's]
    UI
    Catmaid
    ...
    end
    end

    user_bio[Scientist]
    user_bio-->|Upload new data|raw
    user_bio<-->|Interact via website|UI

    user_ai[AI engineer]
    user_ai-->|Upload new models|models

